### ISSUE TITLE
Handle routes between quizzes

### ISSUE THREAD

**Issue by pramodbontha** [tillmo/two_tiered_quiz#103]
The routing between quiz and quiz report needs to handled correct with the URLs

**Comment by tillmo** [comment]
could you please explain the problem in more detail? It is hard to review a PR without having understood the problem completely.

**Comment by pramodbontha** [comment]
Reproducing the Issue.
1. Take a quiz and finish it.
2. Once you are on the report page, click on the back button of browser. Here the URL changes to start of the quiz.
3. Now Refreshing the page makes quiz start again as a new one for the same quiz finished before. When a user submits the quiz, it will be created as a new entry in the database for the same quiz.

The code fix will solve this issue.
