### ISSUE TITLE
Migrations are not commited

### ISSUE THREAD

**Issue by MGlauer** [tillmo/two_tiered_quiz#19]
`makemigrations` should not be part of the setup script. Django's documentation states:

> The migration files for each app live in a “migrations” directory inside of that app, and are designed to be committed to, and distributed as part of, its codebase. You should be making them once on your development machine and then running the same migrations on your colleagues’ machines, your staging machines, and eventually your production machines.

I would recommend to commit and push all migrations in order to keep all databases consistent.

**Comment by jelmd** [comment]
Not sure, whether I got it right. IIRC ruby rails use a similar task to update the database etc.. So what is the correct procedure to get a fork synced with the upstream (this repo) and get a working app [again]? Should I commit the squid-update.sh used on quiz.iks... so we have something to look at?

**Comment by MGlauer** [comment]
Ah, I see that the migrations *are* commited, I guess. It is hard to tell due to #20. But for now it looks fine and I will close this issue
