### ISSUE TITLE
Database should not be under version control

### ISSUE THREAD

**Issue by MGlauer** [tillmo/two_tiered_quiz#20]
The repository seems to contain the entire database. This will lead to severe issues, when multiple people work on the same repository. It may make the code more easily usable, but will potentially lead to very unpleasant merge conflicts.

**Comment by jelmd** [comment]
A environment variable would be good, e.g. DATA_DIR, to point the backend to the directory, which can be used to persist data.

**Comment by tillmo** [comment]
Instead, the db should be filled using a json file.

@jelmd: I have removed your comment and turned it into a separate issue.
