### ISSUE TITLE
python cache and misc generate files/dirs should be ignored by git

### ISSUE THREAD

**Issue by jelmd** [tillmo/two_tiered_quiz#21]
Provide a .gitignore to avoid comiting junk to the repository.

**Comment by tillmo** [comment]
@pramodkumarbontha: in b6f6959b574d1abcdf6def13274e1d9d85f238b8 you have introduced `.pyc` files again (although they are `.gitignored` now). Please remove them.

**Comment by jelmd** [comment]
Not in sync with master?

**Comment by tillmo** [comment]
yes, I am. See https://github.com/tillmo/two_tiered_quiz/tree/master/backend/lqserver/QuizBoard/__pycache__ - this should not be there.

**Comment by jelmd** [comment]
I guess, @pramodkumarbontha's local master is not in sync with the origin/master. Therefore no .gitignore => junk commited. IMHO .gitignore in sub directories are uncommon, but according to gitignore(5) honored: they actually have higher precedence than the patterns from upper dirs ...

**Comment by tillmo** [comment]
OK, I misunderstood. Seems to be fixed now.
