### ISSUE TITLE
Provide overview over results 

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/two_tiered_quiz#52]
Currently, to get the results of the quizz the user needs to click through a hierarchy of answers. There should be a overview which tells the user how many answers he got wrong (and which one). This way the user can go directly to the wrong answers and find out the correct ones. 

(Btw., I would count the combination of the first selection (often "yes" or "no") with the justification as one answer)

**Comment by tillmo** [comment]
@pramodkumarbontha could this easily be displayed together with the score?

**Comment by pramodkumarbontha** [comment]
@tillmo Yes Professor. I am working on the changes. Will let you know once the changes are committed

**Comment by tillmo** [comment]
fixed by #54
