### ISSUE TITLE
Order of navigation button  "Submit Quiz" "Back" "Next" not intuitive

### ISSUE THREAD

**Issue by fabianneuhaus** [tillmo/two_tiered_quiz#53]
Currently, there are three buttons ordered "Submit Quiz" "Back" "Next". On the last question the "Next" button is greyed out.
As Europeans we are used to read from left to right. So the last action (submit) should be to the very right.

**Comment by fabianneuhaus** [comment]
Or alternatively have only two buttons and turn the "Next" button on the last quizz into a "Submit" button.

**Comment by tillmo** [comment]
I prefer to have the "submit" button to the very right. Note that you can submit even if you have not answered all questions. In this case, both "next" and "submit" are active.

**Comment by tillmo** [comment]
@ pramodkumarbontha  I think changing the buttons should be easily and quickly doable.

**Comment by pramodkumarbontha** [comment]
@tillmo Yes Professor. started making the changes

**Comment by tillmo** [comment]
fixed by #54
