### ISSUE TITLE
switch to other database for production

### ISSUE THREAD

**Issue by tillmo** [tillmo/two_tiered_quiz#55]
sqlite3 is not suited for production. Use mysql, mariadb or postgresql.

**Comment by jelmd** [comment]
MySQL database is available. Just provide a way to pickup the database connection parameters:
`DBHOST,  DBPORT, DBNAME, DBUSER, DBPW`. Probably the best is to store them in a separate file (e.g. json formatted) and pass the path to the file via env variable, e.g. `DBPARAMS`.

**Comment by tillmo** [comment]
the parameters can be provided in a local settings file, see #61 
However, please switch to MariaDB, see #56
