### ISSUE TITLE
authentification via JWT

### ISSUE THREAD

**Issue by tillmo** [tillmo/two_tiered_quiz#60]
for user related requests, the frontend needs to authentificate itself to the backend API via JWT

**Comment by tillmo** [comment]
@pramodkumarbontha in `settings.py`, you have already added `rest_framework.authentication.TokenAuthentication`. What is its purpose? 
It seems that currently, anyone can obtain all the data from the API. Access should be restricted via a token here.

**Comment by pramodkumarbontha** [comment]
Will add the authentication to all the URLs

**Comment by tillmo** [comment]
fixed by #72
