### ISSUE TITLE
Redirect http to https

### ISSUE THREAD

**Issue by tillmo** [tillmo/two_tiered_quiz#94]
the http version does not work properly (and is unsafe anyway)

**Comment by jelmd** [comment]
???

**Comment by tillmo** [comment]
http://quiz.iks.cs.ovgu.de/ should automatically redirect to https://quiz.iks.cs.ovgu.de/

**Comment by jelmd** [comment]
Done. (Was just unsure about the http version - can't change anything in the implementation ...)

**Comment by tillmo** [comment]
thanks!
