### ISSUE TITLE
Ergebnisse werden nicht gespeichert

### ISSUE THREAD

**Issue by AcoIyth** [tillmo/two_tiered_quiz#97]
Wenn ich das Quiz absolviere, werden meine Ergebnisse nicht gespeichert. Die Aufgaben werden immer wieder als unbearbeitet angezeigt. Die Punktzahl bleibt trotz richtiger Lösungen in mehreren Aufgaben bei 20 stehen.

**Comment by tillmo** [comment]
Bitte die Seite mit https aufrufen und den Browsercache (ggf. nur für die Seite) löschen.

**Comment by AcoIyth** [comment]
Vielen Dank für den Hinweis, es funktioniert jetzt :)
